// src/lib/features/pagination/components/Pagination.svelte
<script lang="ts" generics="T extends CursorRow">
  /**
   * Keyset pagination: changing `limit` resets cursor/direction (first page at new size).
   */
  import { pushState } from "$app/navigation";
  import { page } from "$app/state";
  import type {
    CursorRow,
    PaginatableItems,
    PaginationSearchParams,
  } from "$features/pagination/types";
  import {
    parseLimitParam,
    toNormalizedListQuery,
  } from "$features/pagination/utils/list-query";
  import { buildListSearchString } from "$features/pagination/utils/url";
  import { buttonVariants } from "$lib/components/ui/button/button.svelte";
  import ChevronLeftIcon from "@lucide/svelte/icons/chevron-left";
  import ChevronRightIcon from "@lucide/svelte/icons/chevron-right";
  import { LIMITS } from "../constants";
  import type { ListDirection } from "../types";

  type Props = {
    store: PaginatableItems<T>;
  };

  let { store }: Props = $props();

  const searchQuery = $derived(page.url.searchParams.get("q") ?? "");
  const limitFromUrl = $derived(
    parseLimitParam(page.url.searchParams.get("limit"))
  );

  const rowItems = $derived(store.items);
  const pageMeta = $derived(store.paginationMetadata);

  const canNavigate = $derived(
    pageMeta.hasNextPage || pageMeta.hasPreviousPage
  );

  const navigateWithQuery = async (next: PaginationSearchParams) => {
    store.presetClientListQueryKey?.(next);
    pushState(`${page.url.pathname}${buildListSearchString(next)}`, {});
    await store.loadItems(next);
  };

  const navigateWithTransition = async (
    next: PaginationSearchParams,
    direction: ListDirection
  ) => {
    if (typeof document?.startViewTransition !== "function") {
      await navigateWithQuery(next);
      return;
    }

    try {
      await document.startViewTransition({
        types: [direction],
        update: () => navigateWithQuery(next),
      }).finished;
    } catch {
      await navigateWithQuery(next);
    }
  };
  const handleForward = async () => {
    const last = rowItems.at(-1);
    if (!last) {
      return;
    }
    const q = searchQuery || undefined;
    const next = toNormalizedListQuery(q, {
      cursor: last.id,
      direction: "forward",
      limit: limitFromUrl,
    });
    await navigateWithTransition(next, "forward");
  };

  const handleBackward = async () => {
    const first = rowItems.at(0);
    if (!first) {
      return;
    }
    const q = searchQuery || undefined;
    const next = toNormalizedListQuery(q, {
      cursor: first.id,
      direction: "backward",
      limit: limitFromUrl,
    });
    await navigateWithTransition(next, "backward");
  };

  const handleLimitChange = async (newLimit: number) => {
    const q = searchQuery || undefined;
    await navigateWithQuery(toNormalizedListQuery(q, { limit: newLimit }));
  };
</script>

{#if rowItems.length === 0 && !store.loading}
  <p class="pe-1 text-right text-sm text-gray-500 italic">No items found</p>
{:else}
  <div class="mbe-6 flex items-center justify-between gap-4">
    <select
      name="limit"
      class={buttonVariants({
        variant: "outline",
        class: "h-10 w-20",
      })}
      disabled={!canNavigate || store.loading}
      onchange={(e) =>
        handleLimitChange(Number((e.currentTarget as HTMLSelectElement).value))}
    >
      {#each LIMITS as limitOption (limitOption)}
        <option
          selected={limitOption === limitFromUrl}
          value={String(limitOption)}>{limitOption}</option
        >
      {/each}
    </select>
    <div class="flex items-center gap-2">
      <button
        type="button"
        class={buttonVariants({ variant: "outline" })}
        aria-label="Previous page"
        disabled={!pageMeta.hasPreviousPage || store.loading}
        onclick={handleBackward}
      >
        <ChevronLeftIcon class="aspect-square inline-4" />
      </button>
      <button
        type="button"
        class={buttonVariants({ variant: "outline" })}
        aria-label="Next page"
        disabled={!pageMeta.hasNextPage || store.loading}
        onclick={handleForward}
      >
        <ChevronRightIcon class="aspect-square inline-4" />
      </button>
    </div>
  </div>
{/if}

// pagination.tsx
import { ChevronLeftIcon, ChevronRightIcon } from "lucide-react";
import { useQueryStates } from "nuqs";
import { startTransition } from "react";
import { Button, buttonVariants } from "~/components/ui/button";
import {
  DEFAULT_LIMIT,
  LIMITS,
} from "~/features/pagination/pagination-constants";
import type { Direction, PaginationProps } from "~/features/pagination/types";
import { validateLimit } from "~/features/pagination/utils/validators";
import { paginationParsers } from "~/lib/parsers";
import type { Id } from "~/types";
import { cn } from "~/utils/utils";

export const Pagination = <T extends Id>({
  items,
  paginationMetadata,
}: PaginationProps<T>) => {
  const [{ limit }, setSearchParams] = useQueryStates(paginationParsers);
  const { hasNextPage, hasPreviousPage } = paginationMetadata;

  // Ensure items is a valid array with items and is not empty
  if (!items || items.length === 0) {
    return (
      <p className="pr-1 text-right text-sm text-gray-500 italic">
        No items found
      </p>
    );
  }

  const handleLimitChange = (newLimit: string) => {
    // Keep cursor unchanged when changing limit - cursor represents position in dataset
    startTransition(async () => {
      await setSearchParams({
        limit: validateLimit(Number(newLimit)),
      });
    });
  };

  const handlePageChange = (direction: Direction) => {
    const item = direction === "forward" ? items.at(-1) : items.at(0);
    if (item) {
      startTransition(async () => {
        await setSearchParams({
          cursor: item.id,
          direction,
        });
      });
    }
  };

  return (
    <div className="my-6 flex items-center justify-between gap-4">
      <select
        className={cn(
          buttonVariants({ variant: "outline", size: "icon" }),
          "w-20"
        )}
        disabled={!(hasNextPage || hasPreviousPage)}
        onChange={(e) => handleLimitChange(e.target.value)}
        value={limit?.toString() ?? DEFAULT_LIMIT.toString()}
      >
        {LIMITS.map((limitOption) => (
          <option key={limitOption} value={limitOption.toString()}>
            {limitOption}
          </option>
        ))}
      </select>
      {/* Navigation buttons */}
      <div className="flex items-center gap-2">
        <Button
          aria-label="Previous page"
          disabled={!hasPreviousPage}
          onClick={() => handlePageChange("backward")}
          size="icon"
          variant="outline"
        >
          <ChevronLeftIcon className="aspect-square w-4" />
        </Button>
        <Button
          aria-label="Next page"
          disabled={!hasNextPage}
          onClick={() => handlePageChange("forward")}
          size="icon"
          variant="outline"
        >
          <ChevronRightIcon className="aspect-square w-4" />
        </Button>
      </div>
    </div>
  );
};
